version: '3.9'

services:
  redis:
    image: 'redis:7-alpine'
    ports:
      - '6379:6379'
  mongodb:
    image: mongo:6.0.3
    ports:
      - '27017:27017'
  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
